export const Users = [
  {
    id:1,
    profilePicture: "/myAssets/person/1.jpeg",
    username: "Deepika Padukon",
  },
  {
    id:2,
    profilePicture: "/myAssets/person/2.jpeg",
    username: "Madhuri Dixit",
  },
  {
    id:3,
    profilePicture: "/myAssets/person/3.jpeg",
    username: "Ranveer Singh",
  },
  {
    id:4,
    profilePicture: "/myAssets/person/4.jpeg",
    username: "Allu Arjun",
  },
  {
    id:5,
    profilePicture: "/myAssets/person/5.jpeg",
    username: "Vijay Thalapathy",
  },
  {
    id:6,
    profilePicture: "/myAssets/person/6.jpg",
    username: "Rashmika ",
  },
  {
    id:7,
    profilePicture: "/myAssets/person/7.jpg",
    username: "Samanntha",
  },
  {
    id:8,
    profilePicture: "/myAssets/person/8.jpg",
    username: "Kiara Advani",
  },
  {
    id:9,
    profilePicture: "/myAssets/person/9.jpeg",
    username: "Siddharth Malhotra",
  },
  {
    id:10,
    profilePicture: "/myAssets/person/10.jpg",
    username: "Priyanka Chopra",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Self love ......is most importanat.❤️❤️",
    photo: "/myAssets/post/1.jpeg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    desc: "Enjoying Vacation......🌈💕",
    photo: "/myAssets/post/2.jpeg",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "Hey Cutie....R u blushing😍",
    photo: "/myAssets/post/3.jpeg",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: "/myAssets/post/4.jpg",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    desc: "This movie is my fvrt🤩.",
    photo: "/myAssets/post/5.jpg",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: "/myAssets/post/6.jpeg",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "Making crazy ideas in my mind...😜",
    photo: "/myAssets/post/7.jpeg",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    desc: "Happy Me...🤭 with my happy Mine😘.",
    photo: "/myAssets/post/8.jpeg",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "Thanks for coming in my life 🌈❤️.",
    photo: "/myAssets/post/9.jpeg",
    date: "5 days ago",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    desc: "Congratulations🎉🎊... to your new journey Parineeti🤗😍💕",
    photo: "/myAssets/post/10.jpeg",
    date: "1 week ago",
    userId: 10,
    like: 104,
    comment: 12,
  },
];
